title: Яой со всего интернета
name: Яой
email: your-email@example.com
description: Основы и нюансы самостоятельной разработки сайтов.
baseurl: ""
url: "https://yaoi-love.ru"
lang: ru

encoding: utf-8
# highlighter: rouge


paginate: 7

permalink: /:categories/:title.html

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  collect:
    output: true
    permalink: /collect/:path/
