title: Яой это красивая любовь двух парней
name: Яой
email: your-email@example.com
description: Основы и нюансы самостоятельной разработки сайтов.
baseurl: "/yaoi-love"
url: "https://dadast.github.io"
lang: ru

encoding: utf-8
# highlighter: rouge


paginate: 7

permalink: /:categories/:title.html

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  collect:
    output: true
    permalink: /collect/:path/
